nodeLinker: pnp

packageExtensions:
  eslint-config-airbnb-base@^14.2.1:
    dependencies:
      eslint: ^7.2.0
      eslint-plugin-import: ^2.22.1
  "@mdx-js/react@^1.6.22":
    dependencies:
      react: ^17.0.0
  "@storybook/addon-measure@^2.0.0":
    dependencies:
      "@storybook/components": ^6.3.0
      "@storybook/core-events": ^6.3.0
      "@storybook/theming": ^6.3.0
  "@storybook/core-client@^6.3.12":
    dependencies:
      webpack: "*"
  "@babel/plugin-syntax-jsx@^7.16.0":
    dependencies:
      "@babel/core": "^7.0.0-0"
  "@babel/plugin-transform-react-jsx@^7.16.0":
    dependencies:
      "@babel/core": "^7.0.0-0"
  "@babel/preset-env@^7.16.0":
    dependencies:
      "@babel/core": ^7.0.0
  fork-ts-checker-webpack-plugin@^4.1.6:
    dependencies:
      typescript: ">= 2.7"
      webpack: ">= 4"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs
